### ISSUE TITLE
Issue with extruder on Biqu CAN setup

### ISSUE THREAD

**Issue by sogeniusio** [bigtreetech/HermitCrab#19]
I'm getting an error every time i try to extrude filament

```
Unable to obtain tmc extruder phase
TMC 'extruder' reports error: DRV_STATUS: 40140020 s2vsb=1(LowSideShort_B!) cs_actual=20 stealth=1
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

Script running error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/filament_switch_sensor.py", line 58, in _exec_gcode
    self.gcode.run_script(prefix + template.render() + "\nM400")
  File "/home/pi/klipper/klippy/gcode.py", line 216, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 272, in cmd_default
    raise gcmd.error(self.printer.get_state_message()[0])
gcode.CommandError: TMC 'extruder' reports error: DRV_STATUS: 40140020 s2vsb=1(LowSideShort_B!) cs_actual=20 stealth=1
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```

```sh
SG_RESULT: 000000ee sg_result=238
1:09 PM
PWM_AUTO: 000e0024 pwm_ofs_auto=36 pwm_grad_auto=14
1:09 PM
PWM_SCALE: 00000012 pwm_scale_sum=18
1:09 PM
PWMCONF: c80d0e24 pwm_ofs=36 pwm_grad=14 pwm_freq=1 pwm_autoscale=1 pwm_autograd=1 pwm_reg=8 pwm_lim=12
1:09 PM
DRV_STATUS: c00f0000 cs_actual=15 stealth=1 stst=1
1:09 PM
CHOPCONF: 34030053 toff=3 hstrt=5 tbl=2 vsense=1 mres=4(16usteps) intpol=1 dedge=1
1:09 PM
MSCURACT: 002300f4 cur_a=244 cur_b=35
1:09 PM
MSCNT: 000000e8 mscnt=232
1:09 PM
TSTEP: 000fffff tstep=1048575
1:09 PM
FACTORY_CONF: 0000000f fclktrim=15
1:09 PM
IOIN: 21000041 enn=1 pdn_uart=1 version=0x21
1:09 PM
OTP_READ: 0000000f otp_fclktrim=15
1:09 PM
IFCNT: 00000031 ifcnt=49
1:09 PM
GSTAT: 00000002 drv_err=1(ErrorShutdown!)
1:09 PM
GCONF: 000001c0 pdn_disable=1 mstep_reg_select=1 multistep_filt=1
1:09 PM
========== Queried registers ==========
1:09 PM
SGTHRS: 00000000
1:09 PM
TPOWERDOWN: 00000014 tpowerdown=20
1:09 PM
TPWMTHRS: 00000000
1:09 PM
IHOLD_IRUN: 0008140f ihold=15 irun=20 iholddelay=8
1:09 PM
SLAVECONF: 00000200 senddelay=2
1:09 PM
========== Write-only registers ==========
1:09 PM
DUMP_TMC STEPPER=extruder
```

**Comment by remigod86** [comment]
Same here: error (GSTAT:      00000002 drv_err=1), loud "clicking" noises and klipper restarts. Could it be that the driver overheats after some time? Earlier, it started working again, until last night, when I've printed for 3 hours (when I woke up, the nozzle was stuck in the printed wall and klipper was showing extruder errors)
